// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fyOgDnMA_N8HbxuT1CkWl1dipIc3Kbw',
    appId: '1:23719618033:web:0c74dc59515fe85d951050',
    messagingSenderId: '23719618033',
    projectId: 'mood-tracker-ryugibo',
    authDomain: 'mood-tracker-ryugibo.firebaseapp.com',
    storageBucket: 'mood-tracker-ryugibo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjbj5fnyrJHYsGYCW4IMJtTziCR9l0Pk',
    appId: '1:23719618033:android:7d00a7f447f0a2ab951050',
    messagingSenderId: '23719618033',
    projectId: 'mood-tracker-ryugibo',
    storageBucket: 'mood-tracker-ryugibo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ly0H78YT2hzJ5sSiQtPDMMggQ2t4GoU',
    appId: '1:23719618033:ios:0642eeef2f2e95d5951050',
    messagingSenderId: '23719618033',
    projectId: 'mood-tracker-ryugibo',
    storageBucket: 'mood-tracker-ryugibo.appspot.com',
    iosBundleId: 'com.example.moodTracker',
  );

}